### ISSUE TITLE
Remove the custom STOPSIGNAL 

### ISSUE THREAD

**Issue by carlba** [zimme/docker-rar2fs#2]
Why do you define a custom SIGTERM in the dockerFile. If the default for the stop signal was used that would allow the mount to be gracefully unmounted when the container is stopped.

**Comment by zimme** [comment]
Nope, that doesn't gracefully shutdown rar2fs. That's why I had to use SIGQUIT, as it was the only signal that would gracefully stop rar2fs and the container.

So unless something's changed in rar2fs this is needed.

**Comment by carlba** [comment]
That is odd for me it works perfectly without the custom signal.

I can see that the share is mounted on container start and unmounted on container stop.

**Comment by zimme** [comment]
@hasse69 Sorry to ping you on this but could you chime in here on what signal is needed to properly stop and unmount rar2fs?

**Comment by hasse69** [comment]
There should be no need for a dedicated signal. The FUSE file system event loop should automatically exit when the mount is removed.

**Comment by hasse69** [comment]
@zimme Can you try some version of rar2fs prior to 1.25.0? I need to check if https://github.com/hasse69/rar2fs/commit/882ed3aac64fd4b13d47f0a060e1e9adb373fa9f possibly broke something.

**Comment by zimme** [comment]
I'll try when I have time. A lot going on at home currently and need to put any extra time I have on another OSS project of mine. Will ping you when I've looked into this

**Comment by zimme** [comment]
I've looked into this a bit more again.

I'm on RancherOS running rar2fs using this Dockerfile.

I've removed the custom stop signal so it defaults to `SIGTERM`.
I've tried with the latest version of rar2fs and version `1.24.1` as Hasse suggested and if I stop the container with these constellations the mount for `/destination` is still present and broken.

```
rancher@storage:/mnt$ ls -la
ls: cannot access 'rar2fs-media': Transport endpoint is not connected
total 25
drwxr-xr-x  4 root root 4096 Apr 14  2019 .
drwxr-xr-x  1 root root 4096 Jun  9 08:49 ..
d?????????  ? ?    ?       ?            ? rar2fs-media
drwxr-xr-x 10 root root   10 Apr 13  2019 storage
rancher@storage:/mnt$
```

This is why I need a custom stop signal `SIGQUIT` as that's the only signal that correctly unmounts the `/destination` volume/mountpoint on container stop.

**Comment by hasse69** [comment]
What version of FUSE are you running in the container?

**Comment by zimme** [comment]
Alpine 3.9.2
fuse 2.9.8

**Comment by hasse69** [comment]
Ok, can you try to manually send SIGTERM to the rar2fs main process using `kill`.
You should see something like this in the syslog
```
Oct 23 23:25:31 media01 rar2fs[13769]: unmounted /home/hasse/project/rar2fs.git/d
```
And your mount point should be empty.

**Comment by zimme** [comment]
I'll have to get back to this some other day, hopefully tomorrow. This might be an issue with using/not using dockers `--init` option. When not using it rar2fs is PID 1 in the container and have to setup signal handling etc itself, using `--init` there's another process `docker-init` or something like that that's PID 1 and handles and forwards signals properly etc.

I'll also try in an alpine/debian VM with docker to see if this is an issue related to rancheros

also, when I ran `kill` on the rar2fs process in the container, when using `--init` rar2fs restarted and the logs just showed mouting /destination again. However I just need to verify the init thing to make sure I didn't mess anything up.

**Comment by zimme** [comment]
So I've tested this again now and for some reason it seems to be working without specifying a stop signal and using the default of SIGTERM.

So I'll push an update with the custom stop signal removed and I'll also update the rar version and rar2fs version if a new version has been released.

**Comment by zimme** [comment]
Custom stop signal removed.
