### ISSUE TITLE
Path to destination is not a shared mount

### ISSUE THREAD

**Issue by Ch0kehold** [zimme/docker-rar2fs#3]
This might be just me being super awful at Linux, but I will post this issue anyway to maybe get some clarity in what needs doing.

I have created the empty directory of `/share/Download/rar2fs` to use for `/destination`.
In accordance with the example given on the dockerhub page, this is the exact command I enter:
```
docker run \
-d --init \
--name rar2fs \
--cap-add SYS_ADMIN \
--cap-add MKNOD \
--device /dev/fuse \
--network none \
--restart always \
-v /volume1/Public/Storage/Stash:/source \
-v /share/Download/rar2fs:/destination:rshared \
zimme/rar2fs
```
However, I get this error message:
`docker: Error response from daemon: linux mounts: path /share/Download/rar2fs is mounted on /share/Download but it is not a shared mount.`
I have attempted to mount the dir to another empty dir with `-o rshared` to make it a shared mount but it's not going anywhere and I am unfortunately running out of ideas on how to make this work.

**Comment by olvier** [comment]
For me an my Synology NAS, I had to make the volume shared first.

This is able to to with

`sudo mount --make-shared /volume1`

Try to start this, with your
`/share/Download/rar2fs`

For me, I have to to this with every reboot of my NAS.

Let me know, if it helps.

Kind regards

**Comment by zimme** [comment]
Hmm, this is weird. I use `...:rshred` in my docker compose file and it works... This error message make it seem like there's already a volume/folder mounted at `/share/Download/rar2fs`. Have you made sure that the rar2fs container is always running before any other container that might mount the same path maybe without `:rshared`?

**Comment by Ch0kehold** [comment]
OK, so almost a year later, I return.

@olvier Your solution worked wonders so now I can run the docker image alongside the other stuff I also use.

@zimme I did not make sure that it runs _before_ anything else, but looking at my docker containers there is absolutely positively nothing else using that path, so getting the error message at all remains weird to me.

Does this qualify to close the issue?

**Comment by olvier** [comment]
In Synology Task-Manager i did this, for mount as _shared_ after every reboot

![image](https://user-images.githubusercontent.com/13106409/137595752-36aadc62-1b6c-4fdd-bc16-62b39f2e1791.png)
![image](https://user-images.githubusercontent.com/13106409/137595761-590c72c3-64ea-4a40-9b83-b0962c711da1.png)

@zimme
Maybe just add the hint, that Synology-User need to make the volumes _shared_ before ;)

Those years ago, it was hard to find a solution for the problem.
Or better: to find the problem ;)

**Comment by zimme** [comment]
Feel free to open a PR with the necessary changes to the README file.

**Comment by igelork** [comment]
just updated my synology from ver. 7.1.xxxx to 7.2.xxxx an run into the same issue... the "sudo mount --make-shared /volume1" solved it for me.

with version 7.1... the containers worked without issue....
