### ISSUE TITLE
docker-compose.example.yml

### ISSUE THREAD

**Issue by thewho2018** [zimme/docker-rar2fs#6]
I'm a first time user of compose.

But before compose i've used rar2fs as a docker on unraid. But some random files get "chown root:root". So I was thinking I would maybe be able to get it sorted with some extra parmas from the compose. Could you add an example to the example file?

**Comment by thewho2018** [comment]
Reason for this request is because some files get root:root ownership. Might be something simpler then my approach.

**Comment by zimme** [comment]
I'm reluctant to add things to this project that will mess with the ownership of your files. This should probably be handled by you on the system where you have the storage to set the proper ownership and then you can use the --user/--group-add options to run as the user/group that have privileges to access the files in the expected manner.

Compose is properly documented so I expect no problems in finding the compose syntax that correlates to --user and --group-add.

**Comment by lmaced0** [comment]
On TrueNAS this only seems to work running as root. When adding a --user flag, I get an error in the logs saying I need to uncomment `#user_allow_other` in /etc/fuse.conf. Which I did, but nothing different happens. Also tried messing with -o uid and gid configs.

@zimme do you have any insights of what might be happening?

**Comment by zimme** [comment]
I would recommend digging into TrueNAS docs regarding file system permission.

TrueNAS is FreeBSD based if I remember correctly unless you're running TrueNAS Scale which is linux based.

Anyway, this is more of a OS + docker related issue and not related to this image. I only give some examples of how you could solve permission related things.

There might be other ways as well.

**Comment by lmaced0** [comment]
> I would recommend digging into TrueNAS docs regarding file system permission.
> 
> TrueNAS is FreeBSD based if I remember correctly unless you're running TrueNAS Scale which is linux based.
> 
> Anyway, this is more of a OS + docker related issue and not related to this image. I only give some examples of how you could solve permission related things.
> 
> There might be other ways as well.

Super thanks! I was able to figure it out.

Creating a restricted ACL dataset within TrueNAS and making the desired user and group owners did the trick. Now Plex can read the rar files and no need to keep the extracting nonsense :D
